// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.


#include "brpc/http_proxy.h"
#include "brpc/http_proxy.pb.h"
#include "brpc/policy/http_proxy_protocol.h"

#include <sstream>
#include <vector>
#include "brpc/channel.h"
#include "brpc/closure_guard.h"
#include "brpc/controller.h"
#include "brpc/errno.pb.h"
#include "butil/strings/string_split.h"
#include "butil/strings/string_util.h"

namespace brpc {
namespace {
class HttpProxyMasterService : public HttpProxyMaster {
public:
    explicit HttpProxyMasterService(std::shared_ptr<HttpProxyService> service)
        : _service(std::move(service)) {}
    void default_method(google::protobuf::RpcController* controller,
                        const HttpProxyRequest*, HttpProxyResponse*,
                        google::protobuf::Closure* done) override {
        _service->Forward(static_cast<Controller*>(controller), done);
    }
    const std::shared_ptr<HttpProxyService>& service() const { return _service; }
private:
    std::shared_ptr<HttpProxyService> _service;
};

// HTTP framing is regenerated by brpc after the body has been decoded. Connection
// options are local to each hop, including extension fields named by Connection.
void RemoveHopHeaders(HttpHeader* header, bool preserve_length = false) {
    const std::string* connection = header->GetHeader("Connection");
    std::vector<std::string> fields;
    if (connection) butil::SplitString(*connection, ',', &fields);
    for (auto& field : fields) {
        butil::TrimWhitespaceASCII(field, butil::TRIM_ALL, &field);
        header->RemoveHeader(field);
    }
    for (const char* field : {"Connection", "Proxy-Connection", "Keep-Alive",
                             "Proxy-Authorization", "Proxy-Authenticate", "TE",
                             "Trailer", "Transfer-Encoding", "Upgrade"}) {
        header->RemoveHeader(field);
    }
    if (!preserve_length) header->RemoveHeader("Content-Length");
}
}  // namespace

google::protobuf::Service* NewHttpProxyMasterService(
    std::shared_ptr<HttpProxyService> service) {
    return service ? new HttpProxyMasterService(std::move(service)) : nullptr;
}

namespace policy {
std::shared_ptr<HttpProxyService> GetHttpProxyService(google::protobuf::Service* master) {
    auto* adapter = dynamic_cast<HttpProxyMasterService*>(master);
    return adapter ? adapter->service() : nullptr;
}
}  // namespace policy

HttpProxyService::HttpProxyService(const HttpProxyOptions& options) : _options(options) {}
HttpProxyService::~HttpProxyService() = default;
bool HttpProxyService::RouteConnect(std::string*, int*) { return true; }

void HttpProxyService::Forward(Controller* controller, google::protobuf::Closure* done) {
    ClosureGuard guard(done);
    const URI& uri = controller->http_request().uri();
    if (!_options.IsValid()) {
        controller->http_response().set_status_code(500);
        return;
    }
    // Forward proxy requests use an absolute HTTP URL. HTTPS uses CONNECT.
    if (uri.scheme() != "http" || uri.host().empty() || !uri.user_info().empty() ||
        !uri.fragment().empty() || uri.port() == 0 || uri.port() > 65535) {
        controller->http_response().set_status_code(400);
        return;
    }
    if (controller->http_request().method() == HTTP_METHOD_CONNECT) {
        controller->http_response().set_status_code(501);  // HTTP/2 CONNECT not implemented.
        return;
    }
    // MakeRawHttpRequest does not transmit GET bodies. Reject rather than drop it.
    if (controller->http_request().method() == HTTP_METHOD_GET &&
        !controller->request_attachment().empty()) {
        controller->http_response().set_status_code(400);
        return;
    }
    ChannelOptions options;
    options.protocol = PROTOCOL_HTTP;
    options.connect_timeout_ms = _options.connect_timeout_ms;
    options.timeout_ms = _options.request_timeout_ms;
    options.max_retry = 0;
    Channel channel;
    std::ostringstream url;
    uri.Print(url);
    if (channel.Init(url.str().c_str(), &options) != 0) {
        controller->http_response().set_status_code(502);
        return;
    }
    Controller upstream;
    upstream.http_request() = controller->http_request();
    RemoveHopHeaders(&upstream.http_request());
    // The absolute request target is authoritative; regenerate Host from it.
    upstream.http_request().RemoveHeader("Host");
    upstream.request_attachment().swap(controller->request_attachment());
    channel.CallMethod(nullptr, &upstream, nullptr, nullptr, nullptr);
    // SetFailed also allocates a synthetic HTTP response header for transport
    // failures, so has_http_response alone does not establish receipt of a
    // response. Completed HTTP error responses report EHTTP or x-bd-error-code.
    const bool origin_error = upstream.ErrorCode() == EHTTP ||
        (upstream.has_http_response() &&
         upstream.http_response().GetHeader("x-bd-error-code"));
    if (upstream.Failed() && !origin_error) {
        controller->http_response().set_status_code(
            upstream.ErrorCode() == ERPCTIMEDOUT ? 504 : 502);
        return;
    }
    upstream.http_response().Swap(controller->http_response());
    controller->http_response().set_version(1, 1);
    RemoveHopHeaders(&controller->http_response(),
                     controller->http_request().method() == HTTP_METHOD_HEAD ||
                     controller->http_response().status_code() == 304);
    controller->response_attachment().swap(upstream.response_attachment());
}
}  // namespace brpc
