// Golden vector tests for KDF and UUID/cmdKey.
// Vectors generated by tools/gen_vectors (calling the Xray-core authoritative
// implementation):
//   KDF16("Demo Key for Auth ID Test", "Demo Path for Auth ID Test")
//     = 66e41ad47fa745fbfd1e97325e93dbf4
//   KDF16(key, "a", "b")          = d924becfdd14cb6634c9fb95e5d22cd1
//   KDF(key, "x")                 = dc642430fa0268f938028c09445f9a5d37c9211b0fa48fb751df5127defce1bf
//   KDF16(00 01 02 03, 01 02 03 04, "bin") = 0212b3681053268251dec507eb331f62
//   KDF16("k")                    = e91da886d57b8f3c65fb8d90fc6c0efc
//   cmdKey(b831381d-6324-4d53-ad4f-8cda48b30811) = b50d916ac0cec067981af8e5f38a758f
//   cmdKey(00000000-…-00000000)              = 5e20f3239545e3f48e0ff445aa7c4c3b
#include <cstdio>

#include "vmess/crypto.hpp"
#include "vmess/kdf.hpp"
#include "vmess/uuid.hpp"

using namespace vmess;

static int failures = 0;

static void check(const char* name, const Bytes& actual, const Bytes& expected) {
    if (actual != expected) {
        std::printf("FAIL %s\n  actual:   %s\n  expected: %s\n", name, to_hex(actual).c_str(),
                    to_hex(expected).c_str());
        ++failures;
    }
}

int main() {
    auto demo_key = as_bytes(std::string_view("Demo Key for Auth ID Test"));

    check("kdf16_1", kdf16(demo_key, {as_bytes("Demo Path for Auth ID Test")}),
          from_hex("66e41ad47fa745fbfd1e97325e93dbf4"));
    check("kdf16_2", kdf16(demo_key, {as_bytes("a"), as_bytes("b")}),
          from_hex("d924becfdd14cb6634c9fb95e5d22cd1"));
    check("kdf32", kdf(demo_key, {as_bytes("x")}),
          from_hex("dc642430fa0268f938028c09445f9a5d37c9211b0fa48fb751df5127defce1bf"));
    {
        Bytes bin_key = {0, 1, 2, 3};
        Bytes bin_path = {1, 2, 3, 4};
        check("kdf16_bin", kdf16(bin_key, {bin_path, as_bytes("bin")}),
              from_hex("0212b3681053268251dec507eb331f62"));
    }
    check("kdf16_empty", kdf16(as_bytes(std::string_view("k")), {}),
          from_hex("e91da886d57b8f3c65fb8d90fc6c0efc"));

    // ---- UUID ----
    {
        auto id = Uuid::parse("b831381d-6324-4d53-ad4f-8cda48b30811");
        check("cmdkey", id.cmd_key(), from_hex("b50d916ac0cec067981af8e5f38a758f"));

        auto zero = Uuid::parse("00000000-0000-0000-0000-000000000000");
        check("cmdkey_zero", zero.cmd_key(), from_hex("5e20f3239545e3f48e0ff445aa7c4c3b"));

        // Case-insensitive and dash-optional parsing
        auto id2 = Uuid::parse("B831381D63244D53AD4F8CDA48B30811");
        if (id.bytes != id2.bytes) {
            std::puts("FAIL uuid case/dash-insensitive parse");
            ++failures;
        }
        bool threw = false;
        try { (void)Uuid::parse("not-a-uuid"); } catch (const Error&) { threw = true; }
        if (!threw) { std::puts("FAIL uuid invalid not rejected"); ++failures; }
    }

    if (failures == 0) std::puts("test_kdf: all passed");
    return failures == 0 ? 0 : 1;
}
